### ISSUE TITLE
support pool.execute and friends

### ISSUE THREAD

**Issue by iomintz** [python-trio/triopg#2]
One of the things I like about asyncpg is its wrappers for common Connection methods, for instance pool.execute:
```py
async def execute(self, query, *args):
    async with self.acquire() as conn:
        return await conn.execute(query, *args)
```

It would be nice if we could have such methods on TrioPoolProxy as well. Is that a possibility? I'd PR this myself but I don't know how dynamic you want it to be. Do you want `__getattr__` or 4 methods corresponding to fetch, fetchval, fetchrow, and execute?

Nice project, btw!

**Comment by touilleMan** [comment]
Hi @bmintz !

That seems like a good idea, your PR is welcome ;-)

> Do you want `__getattr__` or 4 methods corresponding to fetch, fetchval, fetchrow, and execute?

I think having 4 separate methods would be more readable
